/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections1/': RouteRecordInfo<
      '/collections1/',
      '/collections1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections1/i-and-she/': RouteRecordInfo<
      '/collections1/i-and-she/',
      '/collections1/i-and-she',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections1/i-and-she/1': RouteRecordInfo<
      '/collections1/i-and-she/1',
      '/collections1/i-and-she/1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections1/i-and-she/2': RouteRecordInfo<
      '/collections1/i-and-she/2',
      '/collections1/i-and-she/2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections1/i-and-she/3': RouteRecordInfo<
      '/collections1/i-and-she/3',
      '/collections1/i-and-she/3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections1/love-and-peace/': RouteRecordInfo<
      '/collections1/love-and-peace/',
      '/collections1/love-and-peace',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections1/love-and-peace/1': RouteRecordInfo<
      '/collections1/love-and-peace/1',
      '/collections1/love-and-peace/1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections1/love-and-peace/2': RouteRecordInfo<
      '/collections1/love-and-peace/2',
      '/collections1/love-and-peace/2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections1/love-and-peace/3': RouteRecordInfo<
      '/collections1/love-and-peace/3',
      '/collections1/love-and-peace/3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collections1/README': RouteRecordInfo<
      '/collections1/README',
      '/collections1/README',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/girls/': RouteRecordInfo<
      '/girls/',
      '/girls',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/中文分类': RouteRecordInfo<
      '/posts/中文分类',
      '/posts/%E4%B8%AD%E6%96%87%E5%88%86%E7%B1%BB',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/中文Post测试': RouteRecordInfo<
      '/posts/中文Post测试',
      '/posts/%E4%B8%AD%E6%96%87Post%E6%B5%8B%E8%AF%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/你的检验报告总出错': RouteRecordInfo<
      '/posts/你的检验报告总出错',
      '/posts/%E4%BD%A0%E7%9A%84%E6%A3%80%E9%AA%8C%E6%8A%A5%E5%91%8A%E6%80%BB%E5%87%BA%E9%94%99',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/地塞米松': RouteRecordInfo<
      '/posts/地塞米松',
      '/posts/%E5%9C%B0%E5%A1%9E%E7%B1%B3%E6%9D%BE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/寄生虫': RouteRecordInfo<
      '/posts/寄生虫',
      '/posts/%E5%AF%84%E7%94%9F%E8%99%AB',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hello-valaxy': RouteRecordInfo<
      '/posts/hello-valaxy',
      '/posts/hello-valaxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.28.9_magicast@0.5.3_vue@3.5.35_typescript@6.0.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.9_@babel+parser@7.29.7_@nuxt+kit@3.21.6_magicast@0.5.3__@types+markdown-it@14.1.2_2kue2vfrlbs5od6yzix75yo43m/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections1/index.md': {
      routes:
        | '/collections1/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections1/i-and-she/index.md': {
      routes:
        | '/collections1/i-and-she/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections1/i-and-she/1.md': {
      routes:
        | '/collections1/i-and-she/1'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections1/i-and-she/2.md': {
      routes:
        | '/collections1/i-and-she/2'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections1/i-and-she/3.md': {
      routes:
        | '/collections1/i-and-she/3'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections1/love-and-peace/index.md': {
      routes:
        | '/collections1/love-and-peace/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections1/love-and-peace/1.md': {
      routes:
        | '/collections1/love-and-peace/1'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections1/love-and-peace/2.md': {
      routes:
        | '/collections1/love-and-peace/2'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections1/love-and-peace/3.md': {
      routes:
        | '/collections1/love-and-peace/3'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/collections1/README.md': {
      routes:
        | '/collections1/README'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/girls/index.md': {
      routes:
        | '/girls/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.9_magicast@0.5.3_vue@3.5.35_typescript@6.0.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.9_magicast@0.5.3_vue@3.5.35_typescript@6.0.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/中文分类.md': {
      routes:
        | '/posts/中文分类'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/中文Post测试.md': {
      routes:
        | '/posts/中文Post测试'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/你的检验报告总出错.md': {
      routes:
        | '/posts/你的检验报告总出错'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/地塞米松.md': {
      routes:
        | '/posts/地塞米松'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/寄生虫.md': {
      routes:
        | '/posts/寄生虫'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/hello-valaxy.md': {
      routes:
        | '/posts/hello-valaxy'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
